### ISSUE TITLE
Add settings for changing colors

### ISSUE THREAD

**Issue by metaruslan** [orangain/pretty-json-log-plugin#90]
I'd like to configure my own colors. For example, I would definitely make WARNs yellow, because yellow is the color of warnings usually. Currently the plugin makes INFOs yellow.

Great tool, btw!

**Comment by orangain** [comment]
@metaruslan Thank you for using the plugin and submitting feedbacks! You can configure log colors from the **Settings > Editor > Color Scheme > Console Colors > Log console**. I also wonder why JetBrains uses white instead of yellow as the default warning color.

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/873d1716-e8fb-4388-95a2-22a7b0d060bc">

**Comment by metaruslan** [comment]
Oh, I see. Thank you very much!
